# Generated by Django 4.2 on 2023-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
