# Generated by Django 4.2 on 2023-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_alter_remark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='customer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
