# Generated by Django 4.2 on 2023-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_remark_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
