# Generated by Django 4.2 on 2023-06-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_alter_remark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nature_of_business',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('supplier', 'Supplier'), ('trader', 'Trader'), ('retail', 'Retail')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status_of_client',
            field=models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('hot_prospect', 'Hot Prospect'), ('not_interested', 'Not Interested')], max_length=20, null=True),
        ),
    ]
